### ISSUE TITLE
Shovel field tool

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#131]
**BLOCKED BY #133**

This field tool will be be the achievement reward for paying back the loan (#132).

Acceptance criteria:

  - The Shovel is available as a field tool once the achievement described by #132 is complete
  - There is a `SHOVEL` field mode implemented. See: https://github.com/jeremyckahn/farmhand/blob/4438983848f83b4ed937a84548574ba677849449/src/enums.js#L34-L43
  - Selecting the Shovel enables the `SHOVEL` field mode similarly to how other field tools enable their field modes
  - When the `SHOVEL` field mode is enabled, empty plots are highlighted in green similarly to how mature crops are highlighted when the Scythe is selected
  - When the player clicks on such a highlighted plot, it is changed to the "shoveled" state (this will require new art)
  - **This feature is hidden behind a feature flag**

**Comment by lstebner** [comment]
@jeremyckahn what do you think about the field mode being "MINE"? i think that fits with the pattern of the others, but i'm not strongly opinionated here

**Comment by jeremyckahn** [comment]
That sounds good to me!

**Comment by lstebner** [comment]
i have this most of the way there for real this time @jeremyckahn , naming has been rough so far haha. i can go with 'SHOVELED' but after using 'MINE' as the action i went with 'MINED' and the resulting tile being called 'Rubble' but yeah.. i think we should have a quick discussion around naming! also the highlighted color i chose is more orange/yellow, but i'm fine with going with green. check it out though and let me know what you think. 

i also haven't attempted any art, i think that might fit better with #134 since we might want different art for each different outcome.
