### ISSUE TITLE
Bug: Only one notification is shown when multiple recipes are unlocked

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#178]
This is a general and pre-existing bug, but it was surfaced in #176.

**Comment by jeremyckahn** [comment]
This issue is caused by reducer functions calling the `showNotification` reducer multiple times before `latestNotification` is rendered:

https://github.com/jeremyckahn/farmhand/blob/f0d39b2d8260ef6d4df6b23914e9d0002071ab03/src/reducers.js#L1248-L1272

In the case of this bug, it's coming from here: https://github.com/jeremyckahn/farmhand/blob/f0d39b2d8260ef6d4df6b23914e9d0002071ab03/src/reducers.js#L1875-L1897

**Comment by jeremyckahn** [comment]
I think the best solution here is to do what @lstebner [suggested on Discord](https://discord.com/channels/714539345050075176/847884323330850847/876564863676215337) and aggregate these multiple achievement notifications into one. This behavior is an inherent drawback of the design of the `showNotification` reducer's interaction with `notistack` (at least when called by other reducers) and to account for it would necessitate a lot of complex code for a pretty uncommon edge case.

**Comment by jeremyckahn** [comment]
Err, this is actually a bug with recipe notifications, not achievement notifications. 🤦‍♂️

I'm still digging into this!

**Comment by lstebner** [comment]
i got curious, and tried to timebox looking at this but ultimately fell into a little bit of a rabbit hole due to what ended up being an unrelated issue my computer was having. i came up with a little solution though to share. you may have a different one in mind but if anything it could be a starting point - https://github.com/jeremyckahn/farmhand/commit/196fbd9dbd47190479745dad6466093977f486aa
