### ISSUE TITLE
Tool upgrades can be purchased without meeting ingredient requirements 

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/farmhand#271]
Per [this bug report on Discord](https://discord.com/channels/714539345050075176/822068921653788683/961988509424549890):

> you can buy tool upgrades in the forge even if you dont have the materials for them

**Comment by lstebner** [comment]
wanted to summarize the issue/fix here: the issue was that the button was not being disabled, and the subsequent click handler didn't do any checks to see if the upgrade was allowed or not. the current fix adds a disabled attribute to the button, but long term this will move the click handler to be more accessible.
