### ISSUE TITLE
add kegs

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#380]
this idea came up in a [discussion in discord](https://discord.com/channels/714539345050075176/1062561823733325834/1062861056927600911) and needs fleshed out a bit more. i am summarizing the idea here though so it doesn't get lost.

"kegs" could go into a new area of the Workshop and allow for various aged beverages to be made. unlike the recipes that currently exist in the workshop, kegs could be "filled" with an item and then produce a beverage after some number of days (which could vary per beverage). for example, by putting some grapes into one wine could be produced after a few weeks. the produced beverage would have a substantially higher value than the original crop used. 

idea: the player could buy an infinite number of kegs. they could increase in price each like storage does and the kegs screen of the workshop would have a list of all the kegs. each can be filled separately and be on its own timeline. 

alternate idea to infinite kegs: the player purchases a "cellar" that can both be expanded (similarly to the field) in the number of kegs it has, and the keg quality can be upgraded to allow for faster aging.

there should also be some achievements associated to using kegs. i'm sure there's more to consider here so please add any ideas or thoughts you have!

**Comment by jeremyckahn** [comment]
This is a great idea! I think the cellar route might be a bit more scalable than kegs. Treating cellar space similarly to Field or Cow Pen size seems like it would work well and be consistent with the rest of the game. The UI/UX for managing beverages would be simpler if they were treated in bulk, but also the CPU resources needed for unbounded kegs might become unmanageable over time and cause performance issues.

(This is also why we've avoided unbounded Field expansion: The bigger the Field gets, the larger the memory needs and save file becomes. Farmhand needs to run well on lower-powered devices, so it's worth taking that into account when designing new features like this.)

If it's sufficiently complex, we may also want to consider building this feature's UI as a new page (similarly to the Field or Cow Pen), rather than as a tab in the Workshop.
