### ISSUE TITLE
add a chat 

### ISSUE THREAD

**Issue by sjvdvd** [jeremyckahn/farmhand#453]
just so there's actual interaction and people can be friends and other things instead of just knowing people might be there

**Comment by jeremyckahn** [comment]
Hi @sjvdvd, thanks for bringing this up. This has been suggested a number of times on Discord, and historically I've been ambivalent to do it. A lot of kids play Farmhand, and I don't want them inadvertently chatting with strangers via this game. That said, I think there is room for chat functionality so long as it is an **opt-in** feature.

To implement this, I'd like to integrate https://github.com/jeremyckahn/chitchatter into Farmhand since it uses a lot of similar tech and I know the codebase. This would require https://github.com/jeremyckahn/chitchatter/issues/92 to be complete, which is something I'd like to get to in the future.
