### ISSUE TITLE
Show total price when buying/selling

### ISSUE THREAD

**Issue by tim-phillips** [jeremyckahn/farmhand#479]
When buying from the store, it would be nice to see the total price before buying.

**Comment by jeremyckahn** [comment]
Excellent idea @tim-phillips. I've added this to the backlog. I should be able to get to it soon-ish, but let me know if this is something you'd like make a PR for!

**Comment by tim-phillips** [comment]
Thanks! I will if I can figure out this `node-sass` build issue. I swear I've been here before on another project.

**Comment by jeremyckahn** [comment]
> Thanks! I will if I can figure out this `node-sass` build issue. I swear I've been here before on another project.

There might be a Node version mismatch. Are you using v18.12.1? https://github.com/jeremyckahn/farmhand/blob/6968f21f88aa6197c25cbcddc2d6723af8f7b01b/.nvmrc#L1

**Comment by tim-phillips** [comment]
So `node-sass` uses python under the hood and relies on `distutils`, which was removed in the python version I have on my system (v3.12). Once I downgraded to Python 3.11 I was able to run `npm ci` without issue.

**Comment by jeremyckahn** [comment]
> So `node-sass` uses python under the hood and relies on `distutils`, which was removed in the python version I have on my system (v3.12). Once I downgraded to Python 3.11, I was able to run `npm ci` without issue.
> 
> For posterity, the error I was seeing was `ModuleNotFoundError: No module named 'distutils'`, which took me a minute to figure out was python related.

Thanks for sharing your findings here! We may want to explore Dockerizing the dev server and build script so that others can avoid this. That's out of scope for this Issue, certainly.

> How would something like one of the following sit with you?

Thanks for mocking these up @tim-phillips! I like this one as it's a bit simpler visually:

<img alt="Screenshot 2024-01-29 at 2 55 27 PM" width="568" src="https://private-user-images.githubusercontent.com/3578574/300627847-22fe54eb-6c29-434d-b117-89f937b03568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzEwODIsIm5iZiI6MTcwNjU3MDc4MiwicGF0aCI6Ii8zNTc4NTc0LzMwMDYyNzg0Ny0yMmZlNTRlYi02YzI5LTQzNGQtYjExNy04OWY5MzdiMDM1NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMjMyNjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ3YmQxODQyMTE2NTk1YjhlNzQxYTg1NGFkOGVlZDI5NDY0NzkzOGY0NDIyMDI2ODhmM2Q1YTEyYjQyMjdkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-tY8FJNJLTE8h3qtV1bLdmM5ytiot9w6jPNo9-MlJDo">

**Comment by tim-phillips** [comment]
Thanks for the direction, I'll put up a PR!
