### ISSUE TITLE
add .nvmrc

### ISSUE THREAD

**Issue by lstebner** [jeremyckahn/farmhand#69]
since this project desires a specific version of node to be installed, it would be nice to have an .nvmrc to help out with setup.

**Comment by lstebner** [comment]
@jeremyckahn is `v15.14.0` ok?

**Comment by jeremyckahn** [comment]
I love this idea! However, I think we'll need to use the previous LTS (`14.17.0`) because Vercel does not yet support anything higher. I recently tried to upgrade to 15 (the highest that I could get working last time I tried), but had to revert to 14: https://github.com/jeremyckahn/farmhand/commit/b9804b0ede00769528e952aff80e2c61488866a9 😕
